[package]
name = "onboard-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.204", features = ["derive"]}
tokio = {version = "1.39.1", features = ["full"]}
warp = "0.3.7"
reqwest = { version = "0.11", features = ["json"] }